### ISSUE TITLE
color_scheme_path and style not working together

### ISSUE THREAD

**Issue by TheCynicalTeam** [trialuser02/qt6ct#1]
when i use both these settings it doesn't seem to work and be able to use dark mode

**Comment by TheCynicalTeam** [comment]
it does work well with qt6gtk2 though

**Comment by trialuser02** [comment]
What style are you using?

**Comment by TheCynicalTeam** [comment]
i tried both fusion and window i did wanna add adwaita-dark but cant seem to get it to work with qt6 yet

**Comment by TheCynicalTeam** [comment]
using qt6gtk2 and and gtk2 with setting both Standard Dialogs to GTK2 works like a charm though <3

### Qt5

![1609594598](https://user-images.githubusercontent.com/9284733/103458432-ff634780-4cff-11eb-91bd-59ffa2e2a349.png)

### Qt6

![1609594601](https://user-images.githubusercontent.com/9284733/103458438-15710800-4d00-11eb-96a6-dc8d7ac956c0.png)


### My own Qt6 app ([multimonitorlock-gui](https://github.com/TheCynicalTeam/multimonitorlock-gui))

![1609594952](https://user-images.githubusercontent.com/9284733/103458481-99c38b00-4d00-11eb-9277-852c7bdf7e10.png)

**Comment by TheCynicalTeam** [comment]
much better thanks pal
