### ISSUE TITLE
Theme not applying

### ISSUE THREAD

**Issue by advilm** [trialuser02/qt6ct#12]
Hello, I have an issue with theme not applying when I use qt6ct.

I have the environment variables set and, the theme works on qt6ct itself. However it doesn't seem to be affecting other QT applications I have like Dolphin or VirtualBox.

Preview:
![image](https://user-images.githubusercontent.com/40906275/155114019-aed38f6e-767a-4379-8829-1e68c8b71721.png)
I've tried doing `QT_QPA_PLATFORMTHEME=qt6ct virtualbox`, but that doesn't make the theme apply either. I've also tried `QT_QPA_PLATFORMTHEME=qt6gtk2` since it was stated as a possible way to set QT theme to use GTK2 on the arch wiki.

I've tried other methods of applying QT, but the only one I've ever gotten to "work" is kvantum. And even then the UIs are pretty broken. For instance, dark icons on a dark theme when I use dolphin. I've never actually seen a QT theme working well outside of KDE.

**Comment by trialuser02** [comment]
Use qt5ct https://sourceforge.net/projects/qt5ct/ for Qt5 applications

**Comment by advilm** [comment]
So qt6ct only applies themes to Qt6 applications? Is it possible to apply a theme to both Qt5 and Qt6 applications then, or does Qt5 theme apply to Qt6 applications? Since they use the same environment variable to apply.

**Comment by trialuser02** [comment]
qt6ct works with QT_QPA_PLATFORMTHEME=qt5ct. But you should use qt6ct and qt5ct applications to set style for each Qt version.
