### ISSUE TITLE
[abrt] qt6ct: qt_message_fatal(): qt6ct killed by SIGABRT

### ISSUE THREAD

**Issue by martinkg** [trialuser02/qt6ct#15]
Description of problem:
Every time I start it from console

Version-Release number of selected component:
qt6ct-0.5-2.fc36

Additional info:
reporter:       libreport-2.17.1
backtrace_rating: 4
cgroup:         0::/user.slice/user-1000.slice/[user@1000.service](mailto:user@1000.service)/app.slice/app-glib-qt6ct-2743.scope
cmdline:        qt6ct
crash_function: qt_message_fatal
executable:     /usr/bin/qt6ct
journald_cursor: s=b2b1c68c4d6f4957be3c182b0f95f08b;i=d847;b=6446647ebe1e47e99b01761236ceb3b6;m=401a6245;t=5de5ce335cea8;x=e349a00f81518a60
kernel:         5.17.5-300.fc36.x86_64
rootdir:        /
runlevel:       N 5
type:           CCpp
uid:            1000

Truncated backtrace:
Thread no. 1 (9 frames)
 #4 qt_message_fatal at /usr/src/debug/qt6-qtbase-6.2.3-2.fc36.x86_64/src/corelib/global/qlogging.cpp:1905
 #5 QMessageLogger::fatal at /usr/src/debug/qt6-qtbase-6.2.3-2.fc36.x86_64/src/corelib/global/qlogging.cpp:890
 #6 qt_pixmap_thread_test at /usr/src/debug/qt6-qtbase-6.2.3-2.fc36.x86_64/src/gui/image/qpixmap.cpp:81
 #8 QPixmap::QPixmap at /usr/src/debug/qt6-qtbase-6.2.3-2.fc36.x86_64/src/gui/image/qpixmap.cpp:110
 #9 QPixmapIconEngineEntry::QPixmapIconEngineEntry at /usr/src/debug/qt6-qtbase-6.2.3-2.fc36.x86_64/src/gui/image/qicon_p.h:102
 #10 QPixmapIconEngine::addFile at /usr/src/debug/qt6-qtbase-6.2.3-2.fc36.x86_64/src/gui/image/qicon.cpp:463
 #11 QIcon::addFile at /usr/src/debug/qt6-qtbase-6.2.3-2.fc36.x86_64/src/gui/image/qicon.cpp:1113
 #13 QIcon::QIcon at /usr/src/debug/qt6-qtbase-6.2.3-2.fc36.x86_64/src/gui/image/qicon.cpp:729
 #14 IconThemePage::findIcon at /usr/src/debug/qt6ct-0.5-2.fc36.x86_64/src/qt6ct/iconthemepage.cpp:227

[Fedora bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=2082767) with all log files.

**Comment by trialuser02** [comment]
Unable to reproduce under Qt 6.2.4. Are you using static libs?

**Comment by martinkg** [comment]
do you mean against which libraries qt6ct is linked ?
```
[root@fc36 tmp]# ldd /usr/bin/qt6ct 
	linux-vdso.so.1 (0x00007ffceb9ef000)
	libQt6Widgets.so.6 => /lib64/libQt6Widgets.so.6 (0x00007f474538c000)
	libQt6Gui.so.6 => /lib64/libQt6Gui.so.6 (0x00007f4744aa2000)
	libQt6Core.so.6 => /lib64/libQt6Core.so.6 (0x00007f474449a000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f4744266000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f4744246000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f4744045000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f4743f65000)
	libEGL.so.1 => /lib64/libEGL.so.1 (0x00007f4743f52000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f4743f03000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f4743dbb000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f4743c7f000)
	libQt6DBus.so.6 => /lib64/libQt6DBus.so.6 (0x00007f4743ba4000)
	libxkbcommon.so.0 => /lib64/libxkbcommon.so.0 (0x00007f4743b59000)
	libGLX.so.0 => /lib64/libGLX.so.0 (0x00007f4743b27000)
	libOpenGL.so.0 => /lib64/libOpenGL.so.0 (0x00007f4743afc000)
	libpng16.so.16 => /lib64/libpng16.so.16 (0x00007f4743ac2000)
	libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007f47439d9000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f474390b000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f47438ef000)
	libicui18n.so.69 => /lib64/libicui18n.so.69 (0x00007f47435c6000)
	libicuuc.so.69 => /lib64/libicuuc.so.69 (0x00007f47433d3000)
	libsystemd.so.0 => /lib64/libsystemd.so.0 (0x00007f47432f6000)
	libdouble-conversion.so.3 => /lib64/libdouble-conversion.so.3 (0x00007f47432e1000)
	libb2.so.1 => /lib64/libb2.so.1 (0x00007f47432d8000)
	libpcre2-16.so.0 => /lib64/libpcre2-16.so.0 (0x00007f474324c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4745be8000)
	libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007f4743193000)
	libxml2.so.2 => /lib64/libxml2.so.2 (0x00007f4743009000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f4742fdd000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f4742f63000)
	libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00007f4742f0c000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007f4742ef7000)
	libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007f4742ed5000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f4742ec2000)
	libbrotlidec.so.1 => /lib64/libbrotlidec.so.1 (0x00007f4742eb5000)
	libicudata.so.69 => /lib64/libicudata.so.69 (0x00007f4741358000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f474132d000)
	libzstd.so.1 => /lib64/libzstd.so.1 (0x00007f474127a000)
	liblz4.so.1 => /lib64/liblz4.so.1 (0x00007f4741256000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007f474124c000)
	libgcrypt.so.20 => /lib64/libgcrypt.so.20 (0x00007f474110f000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007f47410c3000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f47410bd000)
	libbrotlicommon.so.1 => /lib64/libbrotlicommon.so.1 (0x00007f474109a000)
	libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007f4741074000)
```

**Comment by trialuser02** [comment]
Strange, but QtConcurrent is missing. Here is my ldd output:
`user@myhost:/mnt/DISK1-4/projects/qt6ct-git/src/qt6ct$ ldd qt6ct 
        linux-vdso.so.1 (0x00007ffd9179a000)
        libQt6Widgets.so.6 => /home/user/qt6/lib/libQt6Widgets.so.6 (0x00007852ac970000)
        libQt6Gui.so.6 => /home/user/qt6/lib/libQt6Gui.so.6 (0x00007852ac015000)
        libQt6Concurrent.so.6 => /home/user/qt6/lib/libQt6Concurrent.so.6 (0x00007852ac00e000)
        libQt6Core.so.6 => /home/user/qt6/lib/libQt6Core.so.6 (0x00007852ab9a4000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007852ab946000)
...........................................................................................................................
`

**Comment by martinkg** [comment]
i will build qt6ct with 
`export LDFLAGS="%{optflags} -lQt6Concurrent"` and make it available to the end user for testing.

**Comment by martinkg** [comment]
feedback from the end user.

> In fact, it crashes on finish, not start. When closing program, "Segmentation fault (core dumped)" is displayed. This is with qt6ct.x86_64 0.5-2.fc36.
> 
> Now I will try it with qt6ct-0.5-3.fc36.x86_64.rpm. "Segmentation fault (core dumped)" is also displayed when exiting. But ABRT dialog is not emerging.
> 
> After starting-stopping from console several times, sometimes there is no such error. And one time i got this: "QPixmap: Must construct a QGuiApplication before a QPixmap Aborted (core dumped)".

**Comment by martinkg** [comment]
I am attaching a backtrace that I get when I exit the programme.
[qt6ct-backtrace.txt](https://github.com/trialuser02/qt6ct/files/8660239/qt6ct-backtrace.txt)

**Comment by martinkg** [comment]
new backtrace on exit
[qt6ct_backtrace.txt](https://github.com/trialuser02/qt6ct/files/9469566/qt6ct_backtrace.txt)

**Comment by trialuser02** [comment]
Try latest version from git.

**Comment by trialuser02** [comment]
Try latest version from git.
