### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [trialuser02/qt6ct#21]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [AppearancePage](https://github.com/trialuser02/qt6ct/blob/2b96deb25952eac40e0848ce8ffc55f3dd17df88/src/qt6ct/appearancepage.cpp#L97 "Destructor for AppearancePage")
- [Qt6CTPlatformTheme](https://github.com/trialuser02/qt6ct/blob/24fb43d71428e6603e0b126a491683f118b815d1/src/qt6ct-qtplugin/qt6ctplatformtheme.cpp#L78 "Destructor for Qt6CTPlatformTheme")
- [TroubleshootingPage::on_removeAppButton_clicked](https://github.com/trialuser02/qt6ct/blob/e41923da5723e310310f183dd28dee64293e00ae/src/qt6ct/troubleshootingpage.cpp#L69 "TroubleshootingPage::on_removeAppButton_clicked function")

**Comment by trialuser02** [comment]
If possible, please create merge request for this.

**Comment by elfring** [comment]
:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability/delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by elfring** [comment]
:thought_balloon: [Another update candidate](https://github.com/trialuser02/qt6ct/blob/14a8f91a48b2769425da0b26f05a9ec3a641cc1e/src/qt6ct-qtplugin/qt6ctplatformtheme.cpp#L247 "Update candidate: Qt6CTPlatformTheme::readSettings()") was left over.
