### ISSUE TITLE
Errors during Cmake

### ISSUE THREAD

**Issue by Arndorferd** [trialuser02/qt6ct#3]
Im getting these errors when I try to Cmake this project

The CXX compiler identification is GNU 10.2.0
Detecting CXX compiler ABI info
CMake Warning (dev) at /home/pc/Qt/Tools/CMake/share/cmake-3.19/Modules/CMakeDetermineCompilerABI.cmake:48 (try_compile):
  try_compile given unknown argument "--no-warn-unused-cli".
Call Stack (most recent call first):
  /home/pc/Qt/Tools/CMake/share/cmake-3.19/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)
  CMakeLists.txt:3 (project)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at /home/pc/Qt/Tools/CMake/share/cmake-3.19/Modules/CMakeDetermineCompilerABI.cmake:48 (try_compile):
  COMPILE_DEFINITIONS specified on a srcdir type TRY_COMPILE
Call Stack (most recent call first):
  /home/pc/Qt/Tools/CMake/share/cmake-3.19/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)
  CMakeLists.txt:3 (project)

Detecting CXX compiler ABI info - failed
Check for working CXX compiler: /usr/bin/c++
CMake Error at /home/pc/Qt/Tools/CMake/share/cmake-3.19/Modules/CMakeTestCXXCompiler.cmake:46 (try_compile):
  Failed to set working directory to /CMakeFiles/CMakeTmp/testCXXCompiler.cxx
  : Not a directory
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

Configuring incomplete, errors occurred!
See also "/CMakeFiles/CMakeOutput.log".
See also "/CMakeFiles/CMakeError.log".

**Comment by trialuser02** [comment]
Try latest git version and Qt 6.1-beta3

**Comment by Arndorferd** [comment]
I got it installed but it gives me, qt6ct: error while loading shared libraries: libQt6Widgets.so.6: cannot open shared object file: No such file or directory. When I try running it. I know where this is in my qt file, how do I set the location?

**Comment by trialuser02** [comment]
Use LD_LIBRARY_PATH

**Comment by Arndorferd** [comment]
This isnt an issue anymore you can close it
