### ISSUE TITLE
qt5ct/qt6ct Not working on Wayland

### ISSUE THREAD

**Issue by DarkXero-dev** [trialuser02/qt6ct#34]
Hello

I am a distro maintainer (XeroLinux) on Gnome where I use this tool to theme Qt apps I recently enabled Wayland, unfortunately it ain't working at all .. I tried everything.. 

![image](https://i.imgur.com/GLBKARq.png)

When I do the `echo $QT_QPA_PLATFORMTHEME` command I get nothing. What am I missing ?

**Comment by trialuser02** [comment]
Try to add QT_QPA_PLATFORMTHEME=qt5ct to /etc/environment

**Comment by DarkXero-dev** [comment]
thanks works
