### ISSUE TITLE
Breeze window style

### ISSUE THREAD

**Issue by Arndorferd** [trialuser02/qt6ct#4]
Breeze appears in the qt5ct, it doesn't appear to be in qt6ct. Is there some way to add it?

**Comment by X-m7** [comment]
Pretty sure Breeze itself needs to be updated for Qt6 before it'll show up.

**Comment by TenEXP** [comment]
Breeze supports Qt6 and appears in qt6ct now, I believe this should be closed.

**Comment by Arndorferd** [comment]
Sure, I dont even remember what I was trying to do at the time tbh.
